apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kzrd6hydc-nodejs
  janus-idp.io/tekton: kzrd6hydc-nodejs
  backstage.io/kubernetes-id: kzrd6hydc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kzrd6hydc-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
