apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kzrd6hydc-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5c0e042c73c35ed550a9022da05bb7f179ddefb1@sha256:fcf9d95d795c275b372c5c51cceb0f25d8aa2ce7619fdcd0dcd3a617bc23106d
          name: container-image
